name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.2.0

      - name: Clean build output
        run: rm -rf dist

      - name: Remove lock file and node_modules
        run: rm -rf node_modules package-lock.json

      - name: Install dependencies
        run: npm install

      - name: Install rollup native dependencies (optional)
        run: npm rebuild rollup

      - name: Build
        run: npm run build

      - name: List build output
        run: ls -lhR dist

      - name: Check index.html
        run: test -f dist/index.html && echo "index.html exists" || (echo "index.html missing!" && exit 1)

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
